version: '3.8'

services:
  content-machine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - APP_NAME=${APP_NAME}
      - HOST=${HOST}
      - PORT=${PORT}